# docker-compose.yml
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5434:5432"]


  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_security_auth__minimum__password__length=8
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  mcp-sandbox:
    build: ./services/mcp-sandbox
    ports: ["7001:7001"]
    volumes:
      - ./sandbox:/sandbox

  gateway-api:
    build: ./services/gateway-api
    environment:
      OPENAI_API_KEY: ollama
      OPENAI_API_BASE: http://ollama:11434/v1
      OPENAI_MODEL_NAME: llama3.1:8b
      GATEWAY_GRAPHQL_URL: http://gateway-api:8000/graphql
      DATABASE_URL: postgresql+psycopg2://app:app@postgres:5432/app
      MCP_URL: http://mcp-sandbox:7001
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpassword
    ports: ["8000:8000"]
    depends_on: [postgres, mcp-sandbox, ollama, neo4j]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]
    depends_on: [gateway-api]

volumes:
  ollama:
  neo4j_data: